services:
  postgres:
    image: postgres:17
    container_name: metrics-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: