// Command reset generates Reset methods for marked structures.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "generate:reset"

type packageData struct {
	Name    string
	Structs []structData
}

type structData struct {
	Name       string
	Statements []string
}

func main() {
	// Scan the project and collect marked structures grouped by package.
	packages := make(map[string]*packageData)

	if err := scanProject(".", packages); err != nil {
		fatal(err)
	}

	// Map iteration order is not deterministic, so sort directories.
	dirs := make([]string, 0, len(packages))
	for dir := range packages {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	for _, dir := range dirs {
		if err := generate(dir, packages[dir]); err != nil {
			fatal(err)
		}
	}
}

func scanProject(root string, packages map[string]*packageData) error {
	fset := token.NewFileSet()

	// Walk through the project tree and parse every relevant Go source file.
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if entry.IsDir() {
			// Dependencies and Git metadata are not part of the project code.
			switch entry.Name() {
			case ".git", "vendor":
				return filepath.SkipDir
			default:
				return nil
			}
		}

		name := entry.Name()
		// Ignore tests and files generated by this tool itself.
		if filepath.Ext(name) != ".go" ||
			strings.HasSuffix(name, "_test.go") ||
			name == "reset.gen.go" {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		// Inspect top-level declarations and look for marked structures.
		for _, declaration := range file.Decls {
			genDecl, ok := declaration.(*ast.GenDecl)
			// Check declaration is type
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				// Check type have comment with marker
				if !ok || !hasMarker(genDecl.Doc, typeSpec.Doc) {
					continue
				}

				// Check type have struct
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				dir := filepath.Dir(path)
				pkg := packages[dir]
				if pkg == nil {
					pkg = &packageData{Name: file.Name.Name}
					packages[dir] = pkg
				}

				structure := structData{Name: typeSpec.Name.Name}
				for _, field := range structType.Fields.List {
					for _, fieldName := range fieldNames(field) {
						structure.Statements = append(
							structure.Statements,
							resetStatement("rs."+fieldName, field.Type),
						)
					}
				}

				pkg.Structs = append(pkg.Structs, structure)
			}
		}

		return nil
	})
}

func fieldNames(field *ast.Field) []string {
	// Named fields are stored directly in ast.Field.Names.
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
		return names
	}

	// Embedded fields have no field.Names, so derive the name from the type.
	switch fieldType := field.Type.(type) {
	case *ast.Ident:
		return []string{fieldType.Name}
	case *ast.SelectorExpr:
		return []string{fieldType.Sel.Name}
	case *ast.StarExpr:
		return embeddedPointerName(fieldType.X)
	default:
		return nil
	}
}

func embeddedPointerName(expr ast.Expr) []string {
	// Resolve the name of an embedded pointer such as *User or *pkg.User.
	switch expr := expr.(type) {
	case *ast.Ident:
		return []string{expr.Name}
	case *ast.SelectorExpr:
		return []string{expr.Sel.Name}
	default:
		return nil
	}
}

func hasMarker(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}

		for _, line := range strings.Split(group.Text(), "\n") {
			if strings.TrimSpace(line) == marker {
				return true
			}
		}
	}

	return false
}

func resetStatement(target string, typ ast.Expr) string {
	// Build one reset statement from the field's AST type.
	switch typ := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero(typ.Name); ok {
			return fmt.Sprintf("%s = %s", target, zero)
		}

	case *ast.ArrayType:
		if typ.Len == nil {
			// A slice is represented by ArrayType with a nil Len.
			return fmt.Sprintf("%s = %s[:0]", target, target)
		}

	case *ast.MapType:
		// Clear maps in place to preserve their allocation.
		return fmt.Sprintf("clear(%s)", target)

	case *ast.StarExpr:
		// Pointers require a nil check before resetting their values.
		return resetPointer(target, typ.X)
	}

	// For nested values, call Reset only when the method is implemented.
	return resetIfSupported("&" + target)
}

func resetPointer(target string, element ast.Expr) string {
	// Build reset logic for a pointer while keeping the pointer itself non-nil.
	var body string

	switch element := element.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero(element.Name); ok {
			// Keep the pointer and reset the primitive value it points to.
			body = fmt.Sprintf("*%s = %s", target, zero)
		} else {
			body = resetIfSupported(target)
		}

	case *ast.ArrayType:
		if element.Len == nil {
			// Truncate a pointed-to slice without replacing it.
			body = fmt.Sprintf("*%s = (*%s)[:0]", target, target)
		} else {
			body = resetIfSupported(target)
		}

	case *ast.MapType:
		// Clear the map reached through the pointer.
		body = fmt.Sprintf("clear(*%s)", target)

	case *ast.StarExpr:
		// Support not only *T, but also pointer chains such as **T and ***T.
		body = resetPointer("(*"+target+")", element.X)

	default:
		body = resetIfSupported(target)
	}

	return fmt.Sprintf("if %s != nil {\n%s\n}", target, indent(body))
}

func resetIfSupported(value string) string {
	// Use an interface assertion so types without Reset still compile.
	return fmt.Sprintf(
		"if resetter, ok := any(%s).(interface{ Reset() }); ok {\n\tresetter.Reset()\n}",
		value,
	)
}

func indent(source string) string {
	// Indent a generated multiline statement inside a block.
	return "\t" + strings.ReplaceAll(source, "\n", "\n\t")
}

func primitiveZero(name string) (string, bool) {
	// Return the appropriate zero literal for a built-in primitive type.
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "byte", "rune",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128":
		return "0", true
	default:
		return "", false
	}
}

func generate(dir string, pkg *packageData) error {
	var source bytes.Buffer

	// Write the generated file header and package declaration.
	fmt.Fprintln(&source, "// Code generated by reset; DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n", pkg.Name)

	for _, structure := range pkg.Structs {
		fmt.Fprintf(&source, "\nfunc (rs *%s) Reset() {\n", structure.Name)
		fmt.Fprintln(&source, "if rs == nil {")
		fmt.Fprintln(&source, "return")
		fmt.Fprintln(&source, "}")

		for _, statement := range structure.Statements {
			fmt.Fprintln(&source)
			fmt.Fprintln(&source, statement)
		}

		fmt.Fprintln(&source, "}")
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format generated file for %s: %w", dir, err)
	}

	outputPath := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	return nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "reset:", err)
	os.Exit(1)
}
